name: Deploy Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: privet.robtic.org
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/robtic/robtic-system
            git pull
            ./scripts/deploy.sh